### ISSUE TITLE
Please commit poetry.lock

### ISSUE THREAD

**Issue by Fuuzetsu** [simonlindholm/asm-differ#108]
It's much easier to package/work with the software if this file is committed rather than installing somewhat random version of dependencies (within version bounds). I can of course generate and keep one on my side but if there's a known-working blessed one already used by the developer that basically always works, that'd be best! Thank you.

https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control

**Comment by simonlindholm** [comment]
Generally the dependency versioning strategy of diff.py has been to keep the number of dependencies low enough and depend on stable enough packages that any version of dependencies will work -- this has worked so far, and is convenient because it's easier to tell people to `pip install ...` and `./diff.py ...` than to struggle with venvs. The poetry stuff is mostly there in order to make it easier for decomp.me to use diff.py as a dependency. That said, happy to take a PR that adds a lock file.
